name: LLM Workflow System CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Already using latest major version
      - uses: actions/checkout@v4

      # Already using latest major version
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Run Integration Tests
        run: ./mvnw verify -DskipUnitTests

      - name: SonarCloud Analysis # Corrected name (was SonarQube)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # IMPORTANT: Ensure sonar.organization=nguyenvuhoabinh is set correctly in your pom.xml
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=NguyenVuHoaBinh_prototype9

      - name: Upload Build Artifacts
        # Updated v3 -> v4
        uses: actions/upload-artifact@v4
        with:
          name: service-jars
          path: |
            services/*/target/*.jar
            !services/*/target/*-sources.jar
            !services/*/target/*-javadoc.jar

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Updated v3 -> v4
      - uses: actions/checkout@v4

      # Updated v3 -> v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: OWASP Dependency Check
        run: ./mvnw org.owasp:dependency-check-maven:check

      - name: Upload OWASP Report
        # Updated v3 -> v4
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html